### ISSUE TITLE
Will the fullset be released?

### ISSUE THREAD

**Issue by ddlBoJack** [Sakshi113/MMAU#5]
Congratulations, great work, and future direction for LALM ! 

I want to know if the fullset label (10000 pieces) will be released? Thanks.

**Comment by Sreyan88** [comment]
Hi @ddlBoJack , Similar to MathVista and MMMU, we have decided to keep the 9k answers for the test-set hidden -- we make the [audios](https://drive.google.com/file/d/1XqkRupC723zAeyDn4dYniqNv4uO-8rEg/view) and [questions](https://github.com/Sakshi113/MMAU/blob/main/mmau-test.json) available and you can do evaluation by uploading on [eval.ai](https://eval.ai/web/challenges/challenge-page/2391/overview).

This is done o prevent contamination by future LALMs trained on web-scale data.
