### ISSUE TITLE
Some unfiltered questions in mini-test set

### ISSUE THREAD

**Issue by Andreas-Xi** [Sakshi113/MMAU#6]
Hi,

Thank you for sharing these valuable resources to help advance research in audio LLMs. While working with the mini-test set, we noticed that some of the questions seem to remain unfiltered: 

For instance, the audio file ```90bbd0d8-d08b-47b8-865b-0f7662a12d61``` includes the question:
**"The question can be modified to: 'What seasonal event, often indicated by an increase in bee activity and buzzing, is suggested by the audio?'"**

and similarly, the audio file ```b0a8772a-5c27-47c5-88ac-09d83fc4587b``` is paired with the question: 
**"Modified question: \"Which sound indicates the presence of an animal that is typically known for making low, guttural vocal sounds?""**

Upon review, we found that about 10 questions share a similar pattern, with prefixes like “modified question:”, which could mislead audio LLMs and potentially lead to hallucinations. Could you refine these questions to keep the reliability of the dataset? 

Thanks again for this great work!

**Comment by sonalkum** [comment]
Hi @Andreas-Xi, thank you for bringing this to our attention. We have corrected such instances and will take a couple of more passes to see if we have missed anything else. Thanks once again.
